import { create } from "zustand";

// useEditorStore:  This is a custom hook that provides access to the state and state-modifying functions.
// It is generated by the "create" function, provided by zustand.
const useEditorStore = create((set) => ({
  //  The 'set' function is provided by zustand and is used to update the store's state.
  //  The object you return from the callback to create is the initial state of the store, as well as actions
  //  that can change that state.

  // selectedLayer: This state variable is a string that identifies the currently active layer in the editor.
  //  Possible values: 'canvas' (for the background), or other layer names if they are added later.
  selectedLayer: "canvas",

  // textOptions: This is an object that stores all the settings related to the currently selected text.
  //  It contains the text itself, its font size, color, top and left position.
  textOptions: {
    text: "",        // text: The actual text content.  Initially empty.
    fontSize: 48,    // fontSize: The size of the font, in pixels. Default is 48.
    color: "#000000", // color: The text color, represented as a hexadecimal color code.  Default is black.
    top: 48,        // top: The vertical position of the text relative to its container (e.g., the canvas).  Default is 48 pixels from the top.
    left: 0,         // left: The horizontal position of the text relative to its container.  Default is at the left edge (0 pixels).
  },

  // canvasOptions: This object contains the settings for the background canvas of the editor.
  //  This includes height, orientation, size, and background color.
  canvasOptions: {
    height: 0,        // height: The height of the canvas.  Initially 0 (meaning the canvas's height isn't set).
    orientation: "", // orientation: The orientation of the canvas (e.g., "portrait", "landscape").  Initially not set.
    size: "original", // size: The size of the canvas.  Default is "original", meaning the original aspect ratio.
    backgroundColor: "#008080", // backgroundColor: The color of the canvas's background.  Default is teal.
  },

  // setSelectedLayer: This is a function that updates the 'selectedLayer' state.
  // It takes 'newLayer' (a string) as an argument and updates the store with the new layer.
  setSelectedLayer: (newLayer) => set({ selectedLayer: newLayer }),

  // setTextOptions: This function updates the 'textOptions' state.
  //  It takes 'newOptions' (an object) as an argument and merges it with the current textOptions.
  setTextOptions: (newOptions) => set({ textOptions: newOptions }),

  // addText: This function is a shortcut for adding default text to the editor.
  // This sets the 'textOptions' to a predefined set of default text.
  addText: () =>
    set({
      textOptions: {
        text: "Add text",
        fontSize: 48,
        color: "#000000",
        top: 48,
        left: 0,
      },
    }),

  // setCanvasOptions: This is a function for updating the 'canvasOptions' state.
  // It takes a 'newOption' object (likely containing some or all canvas properties) and updates the store.
  setCanvasOptions: (newOption) => set({ canvasOptions: newOption }),

  // resetStore: This function resets the entire store to its initial state.
  //  It's useful for clearing the editor and starting fresh.
  resetStore: () =>
    set({
      selectedLayer: "canvas",
      textOptions: {
        text: "",
        fontSize: 48,
        color: "#000000",
        top: 48,
        left: 0,
      },
      canvasOptions: {
        height: 0,
        orientation: "",
        size: "original",
        backgroundColor: "#008080",
      },
    }),
}));

export default useEditorStore; // Export the custom hook so other components can use it.
